
export const GET_COLORS_FROM_SERVER = 'GET_COLORS_FROM_SERVER';

export const ADD_COLOR = 'ADD_COLOR';

export const ADD_COLOR_ID_TO_0 = 'ADD_COLOR_ID_TO_0';

export const REMOVE_COLOR_ID_0 = 'REMOVE_COLOR_ID_0';